[workspace]
members = ["recode", "recode-derive", "recode-util"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Ayman Al-Qadhi <alqd@protonmail.com>"]
repository = "https://github.com/real-evolution/recode"
license-file = "LICENSE"
readme = true
publish = true
